### ISSUE TITLE
Fela shorthand expand with merge SSR

### ISSUE THREAD

**Issue by jancama2** [robinweser/fela#789] opened 2020-05-16 15:51 UTC
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela | 11.2.0 |
| react-fela |  11.2.0 | 
| fela-monolithic | 11.2.0 |
| fela-plugin-extend | 11.2.0 |
| fela-plugin-expand-shorthand | 11.2.0 |
| fela-plugin-fallback-value | 11.2.0 |
| fela-plugin-named-keys | 11.2.0 |
| fela-plugin-unit | 11.2.0 |
| fela-plugin-validator | 11.2.0 |

-------------------
#### Description
When using `fela-plugin-expand-shorthand` with merge, an order of atomic classes is different when rendered on a server than on a client. It works properly if merge is turned off.

Honestly I don't know if it is a bug or my own misuse of fela.
#### Steps to reproduce
A rule producing the problem:
```
export const input = ({ theme, disabled = false, error = null, prefix = null, suffix = null }) => {
    const errorStyle = {
        backgroundColor: [theme.colors.error, tinyColor(theme.colors.error).setAlpha(0.08).toRgbString()],
        borderColor: 'transparent',
    };

    const padding = 2 * theme.widths.spacing;
    const paddingWithAddition = additionSize + 2 * theme.widths.spacing;

    const baseStyle = {
        display: 'inline-block',
        boxSizing: 'border-box',

        width: '100%',

        paddingTop: padding,
        paddingBottom: padding,
        paddingLeft: prefix ? paddingWithAddition : padding,
        paddingRight: suffix ? paddingWithAddition : padding,
        marginTop: 0,
        marginBottom: theme.widths.spacing,

        fontFamily: theme.fontFamily.primary,
        fontSize: 0.875,
        lineHeight: 1.14,

        color: theme.colors.text,
        backgroundColor: theme.colors.white,

        border: `1px solid ${theme.colors.midGrey}`,
        borderRadius: '8px',

        isMobile: {
            fontSize: 1,
        },
    };
    const inputStyle = {
        ...baseStyle,
        ':hover': {
            borderColor: theme.colors.grey,
            boxShadow: theme.boxShadows.input,
        },

        ':focus': {
            outline: 'none',
            borderColor: theme.colors.text,
        },

        '::placeholder': {
            color: theme.colors.grey,
        },
    };
    const disabledStyle = {
        ':disabled': {
            color: theme.colors.grey,
            borderColor: 'transparent',
            backgroundColor: theme.colors.midGrey,
            boxShadow: 'none',
        },
    };
    if (disabled) {
        return {
            ...baseStyle,
            ...disabledStyle,
        };
    }
    if (error) {
        return {
            ...inputStyle,
            ...errorStyle,
        };
    }
    return inputStyle;
};
```

#### Expected Behavior
The order of atomic classes remains the same. I can't see a reason for it to be rendered in a different order since the rendered output is the same.

#### Actual Behavior
The error produced by react:
```
index.js:1 Warning: Prop `className` did not match. Server: "bj a c at av fs ft o q t cy fu w cc y fv fw fx fy fz ga gb gc gd ge gf gg gh gi gj gk gl gm gn go gp gq du gr gs gt gu gv gw gx" Client: "bj a c at av fs ft o q t cy fu w cc y fv fw gb gc gd ge fx fy fz ga gf gg gl gm gn go gh gi gj gk gp gq du gr gs gt gu gv gw gx"
    in input (at Input.jsx:32)
```

The misordered classes are classes produced by `:hover` and `:focus` parts of the afore mentioned rule.

**Comment by HugoGiraudel** [comment] 2020-06-04 09:40
Could I ask you to try with `fela-plugin-expand-shorthand@10.6.1`? It should list `inline-style-expand-shorthand@1.1.1` as a dependency in your lock file — **this is very important**, since there was a potential regression (which we failed to really reproduce) in `inline-style-expand-shorthand@1.2.0`.

Let us know if it yields the same result please, as this would help narrowing the problem down. :)

**Comment by robinweser** [comment] 2020-11-06 10:35
I'll close this for now, as it is an issue in `inline-style-expand-shorthand` rather than Fela itself.

**Closed by robinweser** 2020-11-06 10:35 UTC
