### ISSUE TITLE
Storybook won't work with Fela + preact

### ISSUE THREAD

**Issue by matthewharwood** [robinweser/fela#690] opened 2019-03-16 04:04 UTC
https://stackoverflow.com/questions/55193107/invalid-attempt-to-destructure-non-iterable-instance-when-using-fela-css-in-js-w/55193190?noredirect=1#comment97124570_55193190

Im getting an error when I try to render the preact-fela RendererProvider inside storybook
![Error](https://i.stack.imgur.com/44pv5.png)

I def got it working in a non-storybook scenario shown here:

https://codesandbox.io/s/9oj37oyv3r

**To Reproduce**
- Make an instance of preact-storybook.
- `npm install preact-fela preact-context --save`
- open the `.storybook/config` and add:
```
import { configure, addDecorator } from '@storybook/preact';


const req = require.context('../libs', true, /\.story\.js$/);
import { createRenderer } from "fela";
import { createComponent, FelaComponent, RendererProvider } from "preact-fela";

const renderer = createRenderer();
console.log(RendererProvider);
import { h } from 'preact';

addDecorator(story => (
  <RendererProvider renderer={renderer}>
    {story()}
  </RendererProvider>
));


function loadStories() {
  req.keys().forEach(req);
}

configure(loadStories, module);
```

**Comment by rofrischmann** [comment] 2019-04-04 08:31
Hmm. I can't really help here. Storybook works for me with React+Fela and I've only tested Preact without Storybook. Feels like this is some Storybook issue then?

**Comment by matthewharwood** [comment] 2019-04-04 15:55
https://github.com/storybooks/storybook/issues/6122#issuecomment-479956490
Made the issue a while back could you follow up with them too?

**Comment by robinweser** [comment] 2019-11-05 12:43
I'm going to close this for now, since there's no progress (not even sure if the issue still occurs?) and I couldn't really reproduce it in isolation.

**Closed by robinweser** 2019-11-05 12:43 UTC
Labels: Scope: Bindings, Status: Help Wanted
